// Copyright (c) 2026 Viptunbeqwfwew
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org>.

package com.viptunbeqwfwew.deterministicevents;

import java.io.File;
import java.util.HashMap;
import java.util.Map;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import com.viptunbeqwfwew.deterministicevents.asm.CoreDeterministic;
import com.viptunbeqwfwew.deterministicevents.client.ClientProxy;
import com.viptunbeqwfwew.deterministicevents.common.CommonProxy;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.MetadataCollection;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.relauncher.FMLLaunchHandler;

public class DeterministicEvents extends DummyModContainer {

    public static final String MODID = "deterministicevents";
    public static final Logger LOG = LogManager.getLogger(MODID);
    private static final Map<String, Object> extraData = new HashMap<String, Object>() {

        {
            put("name", "Deterministic Events");
            put("version", "GRADLETOKEN_VERSION");
        }
    };

    final public static CommonProxy proxy = (FMLLaunchHandler.side()
        .isServer()) ? new CommonProxy() : new ClientProxy();

    public DeterministicEvents() {
        super(
            MetadataCollection.from(DeterministicEvents.class.getResourceAsStream("/" + MODID + ".info"), MODID)
                .getMetadataForId(MODID, extraData));
        if (getMetadata().autogenerated) {
            LOG.warn("Mod metadata for {} is autogenerated!", MODID);
            getMetadata().autogenerated = false;
        }
    }

    @SuppressWarnings("UnstableApiUsage")
    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        bus.register(this);
        return true;
    }

    @SuppressWarnings({ "unused", "UnstableApiUsage" })
    @Subscribe
    public void preInit(FMLPreInitializationEvent event) {
        proxy.preInit(event);
    }

    @SuppressWarnings({ "unused", "UnstableApiUsage" })
    @Subscribe
    public void startServer(FMLServerStartingEvent event) {
        proxy.startServer(event);
    }

    @Override
    public String getGuiClassName() {
        return proxy.getGuiClassName();
    }

    @Override
    public Object getMod() {
        return this;
    }

    @Override
    public boolean isImmutable() {
        return true;
    }

    @Override
    public File getSource() {
        return CoreDeterministic.source;
    }
}
